rootProject.name = 'devtools'

enableFeaturePreview "STABLE_CONFIGURATION_CACHE"

dependencyResolutionManagement {
    versionCatalogs {
        if (file('gradle/a12-internal.versions.toml').exists()) {
            create('a12Internal') {
                from(files('gradle/a12-internal.versions.toml'))
            }
        }
    }
}

include 'gradle-plugins:build-utilities'
include 'gradle-plugins:prepare-models'
include 'gradle-plugins:prepare-models-validation-converter'
include 'gradle-plugins:integration'
include 'gradle-plugins:validate-data-models'

if (file("internal").exists()) {
    include 'internal'
}

if (file("sharedLibrary").exists()) {
    include 'sharedLibrary'
}

if (file("gradle-plugins/performance-test").exists()) {
    include 'gradle-plugins:performance-test'
}

if (file("gradle-plugins/atlas-security").exists()) {
    include 'gradle-plugins:atlas-security'
}

if (file("gradle-plugins/sbom").exists()) {
    include 'gradle-plugins:sbom'
}

if (file("gradle-plugins/sbom-cleaner").exists()) {
    include 'gradle-plugins:sbom-cleaner'
}

if (file("gradle-plugins/third-party-notices").exists()) {
    include 'gradle-plugins:third-party-notices'
}

file('packages').eachDir { dir ->
    include "packages:${dir.name}"
}